require("custom.terminal")
require("config.options")
require("config.keymaps")
require("config.lazy")
require("config.autocmds")

-- vim.pack.add({ 'https://github.com/vague-theme/vague.nvim' })

-- vim.cmd.colorscheme("retrobox")
-- vim.api.nvim_set_hl(0, "StatusLine", { bg = "NONE" })
-- vim.api.nvim_set_hl(0, "Visual", { fg = "NONE", bg = "#303030" })
-- vim.api.nvim_set_hl(0, "FzfLuaBorder", { fg = "#1c1c1c", bg = "#1c1c1c" })
-- vim.api.nvim_set_hl(0, "FzfLuaBorder", { fg = "#3c3836", bg = "NONE" })
-- vim.cmd.colorscheme "quiet"
-- vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- vim.api.nvim_set_hl(0, "CursorLine", { bg = "none" })
-- vim.api.nvim_set_hl(0, "CursorLineNr", { bg = "none" })
-- vim.api.nvim_set_hl(0, "Visual", { bg = "#805099" })
-- vim.api.nvim_set_hl(0, "Statusline", { bg = "none" })
-- vim.api.nvim_set_hl(0, "IncSearch", { bg = "#805099" })
